# Spring Application Name
spring.application.name=java-medical-platform

# MySQL Datasource Configuration
spring.datasource.url=jdbc:mysql://172.21.121.231:3306/clinic_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=K0uTMc6Wa1eaBaLD5pdGukhE
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate Properties
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# MongoDB Configuration
spring.data.mongodb.uri=mongodb://root:1iDMvQpLzeBbMawDlVhyqZVG@172.21.143.95:27017/clinic_db?authSource=admin
spring.mongodb.uri=mongodb://root:1iDMvQpLzeBbMawDlVhyqZVG@172.21.143.95:27017/clinic_db?authSource=admin

# Static Resource Locations
spring.web.resources.static-locations=classpath:/static/

# Thymeleaf Configuration
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.mode=HTML
spring.thymeleaf.cache=false
spring.thymeleaf.encoding=UTF-8

# JWT Configuration
jwt.secret=SmartClinicSuperSecretKeyForJWTSigning2024XYZ

# API path prefix
api.path=/api/
