# Spring Application Name
spring.application.name=java-medical-platform

# MySQL Datasource Configuration
spring.datasource.url=jdbc:mysql://172.21.149.243:3306/clinic_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=zskxqwpxczMDVo0pqauPSRRn
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate Properties
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# MongoDB Configuration
spring.mongodb.uri=mongodb://root:JvfG14hLYlunuhc1tZRuOh5S@172.21.238.174:27017/clinic_db?authSource=admin

# Static Resource Locations
spring.web.resources.static-locations=classpath:/static/

# Thymeleaf Configuration
spring.thymeleaf.template-resolver.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.mode=HTML
spring.thymeleaf.cache=false
spring.thymeleaf.encoding=UTF-8
